# Generated by Django 5.1.6 on 2025-02-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TECH", "Technology"),
                            ("SCIENCE", "Science"),
                            ("BUSINESS", "Business"),
                            ("FINANCE", "Finance"),
                            ("HEALTH", "Health & Wellness"),
                            ("EDUCATION", "Education"),
                            ("LIFESTYLE", "Lifestyle"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("SPORTS", "Sports"),
                            ("TRAVEL", "Travel"),
                            ("FOOD", "Food & Cooking"),
                            ("PERSONAL", "Personal Development"),
                            ("CAREER", "Career & Work"),
                            ("NEWS", "News & Current Affairs"),
                            ("OPINION", "Opinion & Commentary"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=25,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
