# Generated by Django 5.1.6 on 2025-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_updated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="blogs"),
        ),
    ]
