# Generated by Django 5.1.6 on 2025-02-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog_is_trending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_headline",
            field=models.BooleanField(default=False),
        ),
    ]
