# Generated by Django 5.1.6 on 2025-02-13 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_badge_userbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_blogs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
