# Generated by Django 5.1.6 on 2025-02-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_is_headline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="categories",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs.category",
            ),
        ),
    ]
