# Generated by Django 5.1.6 on 2025-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_category_contactmessage_tag_remove_blog_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
