# Generated by Django 5.1.6 on 2025-02-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_remove_blog_categories_blog_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("blog", "author")},
        ),
    ]
