# Generated by Django 5.1.6 on 2025-02-13 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_blog_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
