# Generated by Django 5.1.6 on 2025-02-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="4163df07-98bf-4835-9afd-67ca255f1021",
                max_length=64,
                unique=True,
            ),
        ),
    ]
