# Generated by Django 5.1.6 on 2025-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="97028493-4ca6-4969-8397-2d0003b6df90",
                max_length=64,
                unique=True,
            ),
        ),
    ]
