# Generated by Django 5.1.6 on 2025-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_comment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("blog", "author")},
        ),
    ]
