# Generated by Django 5.1.6 on 2025-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_comment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied_status",
            field=models.BooleanField(default=False),
        ),
    ]
