# Generated by Django 5.1.6 on 2025-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="7a603ede-8808-49d7-a8c6-7f02cbc7aacb",
                max_length=64,
                unique=True,
            ),
        ),
    ]
