# Generated by Django 5.1.6 on 2025-02-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="3ebbca7f-9845-491b-991b-f09cfa76ab28",
                max_length=64,
                unique=True,
            ),
        ),
    ]
