# Generated by Django 5.1.6 on 2025-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
