# Generated by Django 5.1.6 on 2025-02-14 14:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_alter_profile_verification_token_premiumpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="e7328358-8769-442c-81f5-3167530bb73b",
                max_length=64,
                unique=True,
            ),
        ),
    ]
