# Generated by Django 5.1.6 on 2025-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_alter_blog_image_alter_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="72d763ae-14fd-45a5-90c3-3a4c8afa3093",
                max_length=64,
                unique=True,
            ),
        ),
    ]
