# Generated by Django 5.1.6 on 2025-02-10 18:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordreset",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="reset_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
