# Generated by Django 5.1.6 on 2025-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_passwordreset_created_passwordreset_reset_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
