# Generated by Django 5.1.6 on 2025-02-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="51e50883-7817-4325-9d78-d1ede3c07e6f",
                max_length=64,
                unique=True,
            ),
        ),
    ]
