# Generated by Django 5.1.6 on 2025-02-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_blog_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
