# Generated by Django 5.1.6 on 2025-02-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0013_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="6a1f7897-89e4-4f18-9165-3ca9a8056c23",
                max_length=64,
                unique=True,
            ),
        ),
    ]
