# Generated by Django 5.1.6 on 2025-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_alter_profile_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(
                default="68025688-f4a5-47be-90d1-ebfa753a1412",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="PageVisit",
        ),
    ]
