# Generated by Django 5.1.6 on 2025-02-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_blog_is_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="is_updated",
        ),
        migrations.AddField(
            model_name="blog",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
