# Generated by Django 5.1.6 on 2025-02-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0015_remove_blog_is_updated_blog_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_version",
                        to="blogs.blog",
                    ),
                ),
            ],
        ),
    ]
