# Generated by Django 5.1.6 on 2025-02-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0016_updatedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatedpost",
            name="blog",
            field=models.ForeignKey(
                default=11, on_delete=django.db.models.deletion.CASCADE, to="blogs.blog"
            ),
            preserve_default=False,
        ),
    ]
