# Generated by Django 5.1.6 on 2025-02-11 11:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0017_updatedpost_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
