# Generated by Django 5.1.6 on 2025-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0018_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="x",
            field=models.URLField(blank=True, null=True),
        ),
    ]
