# Generated by Django 5.1.6 on 2025-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0019_profile_facebook_profile_tiktok_profile_twitter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tiktok",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="x",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
