# Generated by Django 5.1.6 on 2025-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0020_alter_profile_facebook_alter_profile_tiktok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
