# Generated by Django 5.1.6 on 2025-02-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0021_profile_instagram"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
